---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: production

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - "recipe[chef-open-data-certificate]"
    data_bags_path: test/data_bags
