name             'chef-open-data-certificate'
maintainer       'The Open Data Institute'
maintainer_email 'tech@theodi.org'
license          'MIT'
description      'Installs/Configures Open Data Certificate nodes'
long_description 'Installs/Configures Open Data Certificate nodes'
version          '0.1.20'

depends 'odi-users'
depends 'lib-curl'
depends 'nodejs'
depends 'mysql'
depends 'memcached'
depends 'rackspace-mysql-proxy'
depends 'odi-nginx'
depends 'odi-deployer'
depends 'nginx'
